### ISSUE TITLE
Create Budget and Set Pricing

### ISSUE THREAD

**Issue by href** [python-summit/sps22#3]
Write a budget that covers our costs and is used as a basis for deciding the ticket price.

- [ ] Gather the costs we have.
- [ ] Propose a budget.
- [ ] Define a ticket price (early bird, regular).

**Comment by chiesax** [comment]
@sfkeller is the price for the Aula always 1200CHF?

I have asked for the Caterina Price List.

Since we do not have Sponsors, I propose that this time the lunch is not included.

**Comment by href** [comment]
For Lunch we might consider including lunch but adding it to the ticket, since I seem to remember that the cafeteria is then able to process everyone quicker. But maybe this is not such an issue anymore with most people using contactless payment. Still, maybe get their input.

Also: Would be nice to know how much it would be to have coffee/tea (say without any croissants or so). As that is another area where we might speed things up if all the attendees do not have to filter through the cafeteria downstairs. That being said - if we can't do it, I'd just let people know up front.
